name: run-lua-tests

on:
  workflow_call:
    inputs:
      lua-version: 
        type: string
        required: true

jobs:
  luarocks-test:
    name: Busted Test, Lua ${{ inputs.lua-version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: ${{ inputs.lua-version }}
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0
      - name: Install test tools
        run: |
          luarocks install busted 
          luarocks install luacov 
          luarocks install luacov-reporter-lcov
      - name: Run luarocks test
        run: |
          luarocks test