name: test-and-publish
on: [push, pull_request]

jobs:
  tests-51:
    uses: ./.github/workflows/run-tests.yml
    with:
      lua-version: 5.1
  tests-52:
    uses: ./.github/workflows/run-tests.yml
    with:
      lua-version: 5.2
  tests-53:
    uses: ./.github/workflows/run-tests.yml
    with:
      lua-version: 5.3
  tests-54:
    uses: ./.github/workflows/run-tests.yml
    with:
      lua-version: 5.4

  publish:
    name: Publish to LuaRocks
    runs-on: ubuntu-latest
    needs: [tests-51, tests-52, tests-53, tests-54]

    steps:
      - name: Publish to LuaRocks
        run: |
          luarocks upload lazylualinq-dev-1.rockspec --force --api-key=${{ secrets.LUAROCKS_API_KEY }}
        if: ${{ github.ref == 'refs/heads/main' }}
