name: tests
on: [push, pull_request]

jobs:
  test:
    name: Test and Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.3"
    
    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Install test tools
      run: |
        luarocks install busted 
        luarocks install luacov 
        luarocks install luacov-reporter-lcov

    - name: test
      run: |
        luarocks test

    - name: Publish to Luarocks
      run: |
        luarocks upload lazylualinq-dev-1.rockspec --force --api-key=${{ secrets.LUAROCKS_API_KEY }}
      if: ${{ github.ref == 'refs/heads/main' }}
